name: generate requirements.txt
on: pull_request


defaults:
  run:
    working-directory: backend

jobs:
  generate-requirements-txt:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        poetry-version: [1.0]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Export requirements.txt
        run: poetry export -f requirements.txt --output requirements.txt
      - name: Update requirements.txt
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: update requirements.txt
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
